### ISSUE TITLE
zef crash installing example under Windows 10

### ISSUE THREAD

**Issue by ToddAndMargo** [finanalyst/p6-inform#4]
Windows 10, build 2004
raku -v
This is Rakudo version 2020.05.1 built on MoarVM version 2020.05
implementing Raku 6.d.

This works perfectly under Fedora 32, but crashes under Windows 10

zef install Informative
===> Searching for: Informative
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Building: Inform:ver<0.1>
[Inform] At line:1 char:192
[Inform] + ... ystem.io.file]::openread((resolve-path $file)))) -replace \"-\",\"\"  ...
[Inform] +                                                                  ~
[Inform] You must provide a value expression following the '-' operator.
[Inform] At line:1 char:192
[Inform] + ... -replace \"-\",\"\" } get-sha256 C:\Users\tony\.zef\store\p6-inform.g ...
[Inform] +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Inform] Unexpected token '\",\"\" } get-sha256 C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\
[Inform] resources\blib\lib\GTK\libatk-1.0-0.dll"' in expression or statement.
[Inform]     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
[Inform]     + FullyQualifiedErrorId : ExpectedValueExpression
[Inform]
[Inform] Effective index out of range. Is: -1, should be in 0..^Inf
[Inform]   in block  at C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\Build.pm line 53
[Inform]   in method build at C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\Build.pm line 47
[Inform]   in block <unit> at -e line 1
[Inform] Actually thrown at:
[Inform]   in block  at C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\Build.pm line 90
[Inform]   in method build at C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\Build.pm line 47
[Inform]   in block <unit> at -e line 1
===> Building [FAIL]: Inform:ver<0.1>
Aborting due to build failure: Inform:ver<0.1> (use --force-build to override)

zef --force-build install Informative
===> Searching for: Informative
===> Building: Inform:ver<0.1>
[Inform] At line:1 char:192
[Inform] + ... ystem.io.file]::openread((resolve-path $file)))) -replace \"-\",\"\"  ...
[Inform] +                                                                  ~
[Inform] You must provide a value expression following the '-' operator.
[Inform] At line:1 char:192
[Inform] + ... -replace \"-\",\"\" } get-sha256 C:\Users\tony\.zef\store\p6-inform.g ...
[Inform] +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[Inform] Unexpected token '\",\"\" } get-sha256 C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\
[Inform] resources\blib\lib\GTK\libatk-1.0-0.dll"' in expression or statement.
[Inform]     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
[Inform]     + FullyQualifiedErrorId : ExpectedValueExpression
[Inform]
[Inform] Effective index out of range. Is: -1, should be in 0..^Inf
[Inform]   in block  at C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\Build.pm line 53
[Inform]   in method build at C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\Build.pm line 47
[Inform]   in block <unit> at -e line 1
[Inform] Actually thrown at:
[Inform]   in block  at C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\Build.pm line 90
[Inform]   in method build at C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\Build.pm line 47
[Inform]   in block <unit> at -e line 1
===> Building [FAIL]: Inform:ver<0.1>
[Inform] Failed to build, but continuing with --force-build
===> Testing: Inform:ver<0.1>
[Inform] # Failed test at t\01-sanity.t line 10
[Inform] # Failed to copy 'C:\Users\tony\.zef\store\p6-inform.git\56d19f8f3b66edcfd4bab24e5bf1403447285e5d\resources\blib\lib\GTK\libgtk-3-0.dll' to 'C:\Users\tony\AppData\Local\Temp\libgtk-3-0.dll': Failed to copy file: no such file or directory
[Inform] # Failed test at t\01-sanity.t line 11
[Inform] # No such method 'show' for invocant of type 'Any'. Did you mean 'so'?
[Inform] # Failed test 'is the correct type'
[Inform] # at t\01-sanity.t line 12
[Inform] # Actual type: Any
[Inform] # You failed 3 tests of 3
===> Testing [FAIL]: Inform:ver<0.1>
Aborting due to test failure: Inform:ver<0.1> (use --force-test to override)

**Comment by finanalyst** [comment]
These failures have been resolved. But Informative still failing to find gtk libraries.
