### ISSUE TITLE
no $?CLASS is available

### ISSUE THREAD

**Issue by ToddAndMargo** [finanalyst/p6-inform#5]
$ raku -c Informative2.pm6
===SORRY!=== Error while compiling /home/CDs/Windows/NtUtil/Informative2.pm6
cannot use a $! parameter in a signature where no $?CLASS is available
at /home/CDs/Windows/NtUtil/Informative2.pm6:40
------>         Str :$!title⏏ = "Inform",
    expecting any of:
        shape declaration

39:     submethod BUILD (
40:        Str :$!title = "Inform",
41:     :@buttons = (),
        :@entries = (),
        GtkWindowPosition :$!position = GTK_WIN_POS_CENTER
        ) {
            my $arg_arr = CArray[Str].new;
            $arg_arr[0] = $*PROGRAM.Str;
            my $argc = CArray[int32].new;
            $argc[0] = 1;
            my $argv = CArray[CArray[Str]].new;
            $argv[0] = $arg_arr;
            for @buttons -> $el {
                @!buttons.push: { :name($el.key), :lable($el.value) }
            };
            for @entries -> $el {
                @!entries.push: { :name($el.key), :lable($el.value) }
            };

            gtk_init($argc, $argv);

            self.init;
        }

Many thanks,
-T

**Comment by finanalyst** [comment]
a) Informative currently is not installing on Windows system
b) Copying the Informative.pm6 code without the BUILD system will not work. Informative has to be installed, so that the dependencies are installed.
